// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VentasNet.Entity.Models
{
    public partial class FormaDePagos
    {
        public FormaDePagos()
        {
            Venta = new HashSet<Venta>();
        }

        public int Id { get; set; }
        public int IdTipoPago { get; set; }
        public string Entidad { get; set; }
        public int IdFinanciacion { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Venta> Venta { get; set; }
    }
}