// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class VentaConfiguration : IEntityTypeConfiguration<Venta>
    {
        public void Configure(EntityTypeBuilder<Venta> entity)
        {
            entity.HasKey(e => e.IdVenta);

            entity.Property(e => e.CantidadProductos)
                .HasMaxLength(10)
                .IsFixedLength();

            entity.Property(e => e.ImporteTotal)
                .HasMaxLength(10)
                .IsFixedLength();

            entity.HasOne(d => d.FormaPagoNavigation)
                .WithMany(p => p.Venta)
                .HasForeignKey(d => d.FormaPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Venta_FormaDePagos");

            entity.HasOne(d => d.IdClienteNavigation)
                .WithMany(p => p.Venta)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("FK_Venta_Cliente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Venta> entity);
    }
}
